### ISSUE TITLE
Internal errors are converted to User errors

### ISSUE THREAD

**Issue by Halama** [keboola/object-encryptor#8]
Padákovi to náhodně při `testConnection` akci db extractoru házelo chybu `Invalid cipher text for key #password Value KBC::ProjectSecure::eJwBNAHL/mE6Mjp `. V samotném nastavení credentials se nic neměnilo a po chvíli to opět začalo fungovat.

Myslím si tedy že něco hodilo internal error při dešifrování, jde o novou KMS šifru.
V kódu jsem narazil na tohle https://github.com/keboola/object-encryptor/blob/376cf02b9472c86ddb6c850d01c6bcbac8aa1769/src/Wrapper/GenericKMSWrapper.php#L202 Imho by to tady mělo hodit `ApplicationException` aby klient mohl udělat retry nebo věděl že došlo k chybě a ne že to nejde rozšiforvat?
A tady https://github.com/keboola/object-encryptor/blob/376cf02b9472c86ddb6c850d01c6bcbac8aa1769/src/Wrapper/GenericKMSWrapper.php#L200 znamená `KmsException` určitě jenom nevalidní metadata?

Při UserException to potom vždy vrátí https://github.com/keboola/object-encryptor/blob/376cf02b9472c86ddb6c850d01c6bcbac8aa1769/src/ObjectEncryptor.php#L157

Ref: https://keboola.zendesk.com/agent/tickets/9354

**Comment by Halama** [comment]
Ještě je teda možnost že to tam nějak zpraseně poslalo UI ale podle té chybové odpovědi to vypadá že ten cipher text tam přišel celý.

**Comment by odinuv** [comment]
dela to retry interne https://github.com/keboola/object-encryptor/blob/376cf02b9472c86ddb6c850d01c6bcbac8aa1769/src/Wrapper/GenericKMSWrapper.php#L188
a v tomhle pripade to byla skutecne interni chyba, je to videt v ex trace
```
CredentialsException (0) in InstanceProfileProvider.php line 88:
Error retrieving credentials from the instance profile metadata server. (cURL error 28: Connection timed out after 1001 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html))
```

jenom by me zajimalo jestli to ten retry opravdu udelalo, v tracu je videt ze se to pres nej posila, ale prijde mi to trosku podezrely, ze by meli tak dlouhy vypadek a nikde jinde se to neprojevilo

> Imho by to tady mělo hodit ApplicationException aby klient mohl udělat retry nebo věděl že došlo k chybě a ne že to nejde rozšiforvat?

no zjevne asi jo, hledal jsem nejakej duvod, ale vypada to, ze to tak proste od zacatku je

> znamená KmsException určitě jenom nevalidní metadata?
jo, celkem jo, ty ostatni veci se checkujou zvlast https://github.com/keboola/object-encryptor/blob/376cf02b9472c86ddb6c850d01c6bcbac8aa1769/src/Wrapper/GenericKMSWrapper.php#L111

> Při UserException to potom vždy vrátí
a melo by to vracet neco jinyho?

**Comment by odinuv** [comment]
tak jsem to overil, retry to skutecne dela, je na to i test https://github.com/keboola/object-encryptor/blob/master/tests/GenericKMSWrapperTest.php#L87 a i ten je funkcni, znamena to teda, ze se to nemohlo nejaky 4s pripojit

**Comment by Halama** [comment]
to jo ale myslím že potom co všechny retry selhaly to mělo vyhodit internal error a né říct že to není cipher text.

**Comment by Halama** [comment]
Kde si našel ten stack trace? myslel jsem že když to je sync akce tak to nikde není.

**Comment by odinuv** [comment]
jojo zmenim to na app error.  

ex trace je normalne v PT, na sync akci neni nic specialniho
